# Generated by Django 5.1.3 on 2024-11-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="caption",
            field=models.TextField(max_length=10000),
        ),
    ]
