# Generated by Django 5.1.3 on 2024-12-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="password",
        ),
    ]
