# Generated by Django 5.1.3 on 2024-12-03 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_contact_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="user",
        ),
    ]
