# Generated by Django 5.1.3 on 2024-12-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_contact_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(default=-2033, max_length=50),
            preserve_default=False,
        ),
    ]
