# Generated by Django 5.1.3 on 2024-12-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
